//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duyuru
    {
        public int duyuruID { get; set; }
        public Nullable<System.DateTime> duyuruZaman { get; set; }
        public string duyuruTitle { get; set; }
        public string duyuruIcerik { get; set; }
        public Nullable<int> duyuruSira { get; set; }
        public Nullable<bool> duyuruDurum { get; set; }
    }
}
