//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Masor()
        {
            this.RezervasyonSpas = new HashSet<RezervasyonSpa>();
        }
    
        public int masorID { get; set; }
        public string masorAdSoyad { get; set; }
        public string masorTC { get; set; }
        public Nullable<bool> masorCinsiyet { get; set; }
        public Nullable<System.DateTime> masorDogTar { get; set; }
        public Nullable<int> spaID { get; set; }
        public string masorTel { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> masorDurum { get; set; }
    
        public virtual Spa Spa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezervasyonSpa> RezervasyonSpas { get; set; }
    }
}
