//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteri()
        {
            this.RezervasyonActivites = new HashSet<RezervasyonActivite>();
            this.RezervasyonSpas = new HashSet<RezervasyonSpa>();
        }
    
        public int musteriID { get; set; }
        public Nullable<int> odaID { get; set; }
        public string musteriAdi { get; set; }
        public string musteriSoyadi { get; set; }
        public string musteriTC { get; set; }
        public string musteriTelefon { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> musteriDurum { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> musteriTip { get; set; }
        public Nullable<System.DateTime> musteriDogTar { get; set; }
        public Nullable<bool> musteriCinsiyet { get; set; }
    
        public virtual Oda Oda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezervasyonActivite> RezervasyonActivites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezervasyonSpa> RezervasyonSpas { get; set; }
    }
}
