//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RezervasyonActivite
    {
        public int rezervasyonID { get; set; }
        public Nullable<int> activiteID { get; set; }
        public Nullable<int> musteriID { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> kisiSayisi { get; set; }
        public Nullable<System.DateTime> createAt { get; set; }
        public Nullable<System.DateTime> updateAt { get; set; }
        public string rezervasyonİcerik { get; set; }
    
        public virtual Activite Activite { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
