//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int sepetID { get; set; }
        public int urunID { get; set; }
        public Nullable<int> urunMiktar { get; set; }
        public Nullable<int> odaID { get; set; }
        public Nullable<double> urunToplamFiyat { get; set; }
        public Nullable<bool> SepetDurum { get; set; }
        public Nullable<System.DateTime> SepetZaman { get; set; }
        public string isSelected { get; set; }
        public Nullable<int> odemeID { get; set; }
    
        public virtual Oda Oda { get; set; }
        public virtual Urun Urun { get; set; }
        public virtual OdemeTip OdemeTip { get; set; }
    }
}
