//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sipari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sipari()
        {
            this.SiparisDetays = new HashSet<SiparisDetay>();
        }
    
        public int siparisID { get; set; }
        public Nullable<int> odaID { get; set; }
        public Nullable<System.DateTime> siparisZaman { get; set; }
        public Nullable<double> siparisToplam { get; set; }
        public Nullable<int> siparisNo { get; set; }
        public Nullable<bool> isSelected { get; set; }
        public Nullable<bool> odemeTip { get; set; }
    
        public virtual Oda Oda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetays { get; set; }
    }
}
