//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spa()
        {
            this.Masors = new HashSet<Masor>();
        }
    
        public int spaID { get; set; }
        public string spaAd { get; set; }
        public string spaAciklama { get; set; }
        public string spaResim { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<decimal> spaFiyat { get; set; }
        public string spaSuresi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Masor> Masors { get; set; }
    }
}
