//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taksi
    {
        public int taksiID { get; set; }
        public string taksiDurakAd { get; set; }
        public string taksiAd { get; set; }
        public string taksiTelefon { get; set; }
        public string taksiAdres { get; set; }
    }
}
