//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WifiMesaj
    {
        public int wifiMesajID { get; set; }
        public Nullable<int> wifiID { get; set; }
        public string wifiText { get; set; }
        public Nullable<int> wifiBildirimSayi { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Wifi Wifi { get; set; }
    }
}
